apiName: "Lifestyle API"

assets:
  mappings:
    /assets: /
  overrides:
    /: ../ipsen3-lifestyle-client/

server:
  rootPath: /api/*
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
      
logging:
  level: INFO
  loggers:
    org.eclipse.jetty: INFO
    io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG
